### PR TITLE
Update Make_PKG.bat

### PR DESCRIPTION
**Pull request by ghost**
This version uses more descriptive variable names and a consistent naming convention. It also puts quotes around paths with spaces and uses forward slashes consistently. Finally, it adds error handling that checks the exit code of the make pkg command and exits the script if it fails.

### CODE REVIEW

**Comment by aldostools** [comment]
It doesn't work. You have set wrong quotes in set PATH="..."

Not approved.

**Comment by PotatoMasherGUI** [comment]
Do you have MinGW and MSYS installed?

**Comment by PotatoMasherGUI** [comment]
Never mind, am I able to re-edit the pull request? Maybe I can fix it :/

**Comment by ghost** [comment]
I wrote the code with vb instead of .bat, MB I'll fix the error

**Comment by aldostools** [comment]
Sorry, but the new .bat doesn't work either. The first at least worked after removing the extra quotes.

Not approved. Honestly I don't know why you want this changed. Nobody complained about it and the changes doesn't provide additional benefits, except waste my time.

**Pull request closed without merging**
